# -*- coding: utf-8 -*-
"""baekjoon_5347.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CXsODU6cOYM9lP8omD8CDXq6C-snayF3
"""

from math import lcm

def solution(inp):
    n1, n2 = map(int, inp.split())
    res = lcm(n1, n2)

    return res

for _ in range(int(input())):
    inp = input()
    print(solution(inp))