# -*- coding: utf-8 -*-
"""baekjoon_2609.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G33DpQHt5U2Qj3Te4ExqjDolilsXkCSk
"""

import math

a, b = map(int, input().split())

print(math.gcd(a, b))
print(math.lcm(a, b))