# -*- coding: utf-8 -*-
"""baekjoon_11728.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fth8zJy4WiHZfgbwSZBdryebtKUn6zwc
"""

def union(nums,inputs):
    n1, n2 = map(int, nums.split())
    ls = []
    for n, i in zip(range(2),[n1,n2]):
        var = map(int, inputs[n].split())
        for k in var:
            ls.append(k)
    ls.sort()
    for j in range(len(ls)):
        print(ls[j], end=' ')
def test_union():
    assert union('2 1', ['4 7','1']) == '1 4 7'