# -*- coding: utf-8 -*-
"""baekjoon_1934.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Qrd00vQiL3QwosrGrnCkRShim9tS4h6
"""

import sys

T=int(input())

for i in range(T):
    a,b=map(int,sys.stdin.readline().strip().split())
    aa,bb=a,b

    while bb!=0:
        aa=aa%bb
        aa,bb=bb,aa

    print(a*b//aa)