# -*- coding: utf-8 -*-
"""review_baekjoon_2675.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ztZRoX2Ij4ajyhWLvPRTtyBTDtL0t-52
"""

# review_baekjoon_2675.py
'''
# [0] 테스트 케이스의 개수 입력 및 문자열 입력
T      = int(input())
String = input()
String = String.strip()

# [1] 출력
for i in String:
    for _ in range(T):
        print(i, end = "")     
'''

def sr_rp(s):
    result = ''
    String = s
    n, String = String.split()


    for i in String:
        for _ in range(int(n)):
            result += i 
    return result

# T      = int(input())
# for _ in range(T):
#     sr_rp(input())

# 테스트 코드
def test_sr_rp():
    assert sr_rp('5 /HTP') == '/////HHHHHTTTTTPPPPP'