# -*- coding: utf-8 -*-
"""test_baekjoon_9012_try_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SabJMgb-oTYviq2yBqXKG40pyUz44nr8
"""

def VPS(tarls):
    result = ''
    for tar in tarls:
        target = list(tar.strip())
        temp = []
        for x in target:
            if x == "(":
                temp.append(x)
            else:
                if len(temp) == 0:
                    temp.append(x)
                    break
                else: temp.pop()

        if len(temp) == 0:
            result += "YES "
        else: result += "NO "
        return result

tarls = ['(())())','(((()())()','(()())((()))','((()()(()))(((())))()','()()()()(()()())()','(()((())()(']

def test_VPS():
    assert VPS(tarls) == 'NO NO YES NO YES NO '