# -*- coding: utf-8 -*-
"""test_baekjoon_16401.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10fq2uUhTVg4TVm35spV3UYAVCwgXNYqm
"""

def devide_snack(input1,input2):
    pn, sn = map(int, input1.split())
    ls = list(map(int,input2.split()))
    left = 1 # 0으로 시작하면 zerodevisionError 발생
    right = max(ls)
    while left <= right:
        count = 0
        mid = (left + right)//2
        for k in ls:
            if k >= mid:
                count += k//mid
        if count >= pn:
            left = mid + 1
        elif count < pn:
            right = mid - 1
    return right

def test_devide_snack():
    assert devide_snack('3 10','1 2 3 4 5 6 7 8 9 10') == 8