# -*- coding: utf-8 -*-
"""test_baekjoon_1764_try_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dEymQ8i-CmyTkcBY2WT8aYqfiYM7omE3
"""

def eqch(lls, sls):
    result = []
    sls.sort()
    for k in lls:
        left, right = 0, (len(sls)-1)
        while left <= right:
            mid = (left + right)//2
            if k == sls[mid]:
                result.append(k)
                break
            elif k > sls[mid]:
                left = mid + 1
            elif k < sls[mid]:
                right = mid - 1
    result.sort()
    return len(result), result
def test_eqch():
    assert eqch(['ohhenrie','charlie','baesangwook'],['obama','baesangwook','ohhenrie','clinton']) == (2 , ['baesangwook','ohhenrie'])