# -*- coding: utf-8 -*-
"""test_baekjoon_1654.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j-7YshsQ-KMLjwsCnyCabqSeU-dCXD-9
"""

def cutlen(num, nth, ls):
    result = []
    left, right = 1, max(ls)
    while left <= right:
        mid = (left + right) // 2 
        lines = 0
        for i in ls:
            lines += i // mid
            
        if lines >= nth:
            left = mid + 1
        else:
            right = mid - 1
    return right
def test_cutlen():
    assert cutlen(4, 11, [802,743,457,539]) == 200