# -*- coding: utf-8 -*-
"""test_baekjoon_14490.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12hByARV6Q2PFOzoNp_pmv3Wg7OHLzXql
"""

from math import gcd

def solution(string):
    num1, num2 = map(int, string.split(":"))

    gcd_num = gcd(num1, num2)

    return f"{num1 // gcd_num}:{num2 // gcd_num}"

def test_solution():
    assert solution("100:10") == "10:1"