# -*- coding: utf-8 -*-
"""test_baekjoon_2164.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v4IPlOfY4UOngysTX0PAtiwPDendIQP7
"""

from collections import deque
def card(inp):
    que = deque(range(1,(inp+1)))
    while len(que) != 1:
        que.popleft()
        x = que.popleft()
        que.append(x)
    return que.pop()

def test_card():
    assert card(6) == 4