# -*- coding: utf-8 -*-
"""test_baekjoon_2805_try_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yKcCOIrqYDfPNlRqfNCl7Erwx0en-r_J
"""

def treelen(M, trees):
    start, end = 0, max(trees) 

    while start <= end:
        mid = (start+end)//2
        tree = 0 
        for i in trees:
            if i > mid: 
                tree += i - mid

        if tree >= M: 
            start = mid + 1
        else: 
            end = mid - 1
    return end
    
def test_treelen():
    assert treelen(7, [20,15,10,17]) == 15