# -*- coding: utf-8 -*-
"""test_baekjoon_2075.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gl8lLKvAZqJqd_hKpVhCR8xTEJQpP0_s
"""

import sys, heapq
def nthnum(num, ls):
    heap = []
    for i in range(num):
        x = list(map(int, ls[i].split()))
        if len(heap) < num:
            heap = x
        else:
            for k in x:
                if heap[0] < k:
                    heapq.heappop(heap)
                    heapq.heappush(heap,k)
    return heap[0]
def test_nthnum():
    assert nthnum(5, ['12 7 9 15 5','13 8 11 19 6','21 10 26 31 16','48 14 28 35 25','52 20 32 41 49']) == 35