# -*- coding: utf-8 -*-
"""test_baekjoon_2751.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ssr-6VXDxZfRQa2EOiGk8-6yBH7vsHLO
"""

import sys
def sort_num(n,target):
    num = int(n)
    target = target
    target.sort()
    return target

def test_sort_num():
    assert sort_num(5,[5,4,3,2,1]) == [1,2,3,4,5]