# -*- coding: utf-8 -*-
"""test_baekjoon_7795_try_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NjXrony04ioUGtyL6QklPX4V3T6rFVC0
"""

def eatneat(N, M, A, B):
    sum=0
    A.sort(reverse=True) # 내림차순 정렬
    B.sort(reverse=True) # 내림차순 정렬
    a=0
    b=0
    n=len(A)
    m=len(B)
    while a < n and b < m: # n,m 범위 안에서 반복
        if A[a] > B[b]: # A종의 크기가 B종의 크기보다 클 때
            sum += m - b # b번째 B가 a번째 A보다 작을 때 b번째를 포함한 남은 물고기 개수는 m-b
            a += 1
        else:
            b += 1
        
    return sum

def test_eatneat():
    assert eatneat(2, 5, 3, [8,1,7,3,1],[3,6,1]) == 7