# -*- coding: utf-8 -*-
"""test_baekjoon_10867.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14_Wb9RFwGpMwqQDmaLMPG_2RZxCLngIk
"""

def sortme(nums):
    ls = list(map(int,nums.split()))
    ls = list(set(ls))
    ls.sort()
    return ls
def test_sortme():
    assert sortme('1 4 2 3 1 4 2 3 1 2') == [1,2,3,4]