# -*- coding: utf-8 -*-
"""test_baekjoon_2110.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bnUAq6n6018xq57rR7Rcnk1KgpcY_VFA
"""

def binary(share, ls):
    ls.sort()
    left = 1
    right = max(ls) - 1

    while left <= right:
        mid = (left + right) // 2

        count = 1
        wifi = min(ls) + mid

        for i in range(1, len(ls)):
            if wifi <= ls[i]:
                count += 1
                wifi = ls[i] + mid

        if count >= share:
            left = mid + 1
        elif count < share:
            right = mid -1
    return right

def test_binary():
    assert binary(3, [1, 2, 8, 4, 9]) == 3