# -*- coding: utf-8 -*-
"""test_baekjoon_1427.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ilgNLtt8rkeZLlQgI5elBv9krcmHH0F
"""

import sys
def sort_inside(num):
    ls = [0] * len(num)
    for i in range(len(num)):
        ls[i] = num[i]
    ls.sort(reverse=True)
    result = ''
    for k in range(len(num)):
        result += str(ls[k])
    print(result)
def test_sort_inside():
    assert sort_inside('2143') == '4321'