# -*- coding: utf-8 -*-
"""test_backjoon_2512.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14mWbfuRVG0mFC7xpIwDBFJXxU2t_8b4B
"""

def budget(n, ls, lim):
    left = 1
    right = max(ls)
    while left <= right:
        sum = 0
        mid = (left + right)//2

        for k in ls:
            if k >= mid:
                sum += mid
            elif k < mid:
                sum += k
        if sum <= lim:
            left = mid + 1
        elif sum > lim:
            right = mid - 1
    return right

def test_budget():
    assert budget(4, [120, 110, 140, 150], 485) == 127