# -*- coding: utf-8 -*-
"""test_baekjoon_5347.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/187exZNKKIdN-3YSvnVXgQKIabjApoVZ6
"""

from math import lcm

def solution(inp):
    n1, n2 = map(int, inp.split())
    res = lcm(n1, n2)

    return res

def test_solution():
    result = ''
    inps = ['15 21','33 22','9 10']
    for rep, inp in zip(range(3), inps): 
        solution(inp)
        if (rep+1) == len(inps):
            result += str(solution(inp))
        else:
            result += str(solution(inp)) + " "
    
    assert result == '105 66 90'