# -*- coding: utf-8 -*-
"""test_baekjoon_1181.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wFdMNSr5zMDIyHhmpDnkZUwkW364jaPg
"""

def wordsort(num,words):
    ls = []
    for i in range(num):
        ls.append(words[i])
    ls = set(ls)
    ls = list(ls)
    ls.sort(key= lambda x: (len(x),x))
    result = ''
    for k in range(len(ls)):
        if k == (len(ls)-1):
            result += ls[k]
        else:
            result += ls[k] + ' '
    return result

def test_wordsort():
    assert wordsort(13, ['but','i','wont','hesitate','no','more','no','more','it','cannot','wait','im','yours']) == 'i im it no but more wait wont yours cannot hesitate'