# -*- coding: utf-8 -*-
"""test_baekjoon_10818.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TfGbCeieLiSTtzNpQu2I-FhCHXa1mFlz
"""

def minnmax(s,num):
    ls = s.split()
    max = -1000000
    min = 1000000

    for i in range(num):
        if int(ls[i]) > max:
            max = int(ls[i])
        else:
            pass
        if int(ls[i]) < min:
            min = int(ls[i])
        else:
            pass
    return min, max

def test_minnmax():
    assert minnmax('20 10 35 30 7',5) == 7, 35