# -*- coding: utf-8 -*-
"""test_baekjoon_16212.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BAM1HYdzDi-_AZLE8VPA5cvFjQpDlMzM
"""

def sortnum(n, input):
    n = int(n)
    ls = [0] * n
    for i, t in zip(range(n), map(int,input.split())):
        ls[i] = t
    ls.sort()
    result = ''
    for i, k in zip(range(n) ,ls):
        if i == (n-1):
            result += str(k)
        else:
            result += str(k) + ' '
    return result
def test_sortnum():
    assert sortnum('6','14 5 8 7 1 10') == '1 5 7 8 10 14'