# -*- coding: utf-8 -*-
"""test_baekjoon_5635.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NhiuaClZX-7uW49cLgmkPv6FRmg-pSPS
"""

def birthsort(num,input):
    ls = []
    for i in range(num):
        [name,day,month,year] = input[i].split()
        ls.append([name,int(day),int(month),int(year)])
    ls.sort(key = lambda x:(x[3],x[2],x[1]))
    return ls[-1][0], ls[0][0]

def test_birthsort():
    birthsort(5,['Mickey 1 10 1991','Alice 30 12 1990','Tom 15 8 1993','Jerry 18 9 1990','Garfield 20 9 1990']) == 'Tom','Jerry'