# -*- coding: utf-8 -*-
"""test_baekjoon_1406_try_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uOLc7wdN-jdEnFHfzEt_J46vadKeS3UQ
"""

import sys
def editor(inp, n, ls):
    stack_l = list(inp)
    stack_r = []

    for i in ls):
        command = i.split()

        if command[0] == "L" and stack_l:
            stack_r.append(stack_l.pop())
        elif command[0] == "D" and stack_r:
            stack_l.append(stack_r.pop())
        elif command[0] == "B" and stack_l:
            stack_l.pop()
        elif command[0] == "P":
            stack_l.append(command[1])

    result = "".join(stack_l + list(reversed(stack_r)))
    return result

def test_editor():
    assert editor('abcd',3,['P x','L','P y']) == 'abcdyx'