# -*- coding: utf-8 -*-
"""test_baekjoon_3986.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XhKHmmSO9d72GfIoGFA0-jbB4s2j1CJo
"""

def check(word):
    temp = []
    for i in range(len(word)):
        if temp and temp[-1] == word[i]: # 전에 나온 글자와 현재 글자가 같은 경우 pop
            temp.pop()
            print(temp)
        else:
            temp.append(word[i]) # 전에 나온 글자와 현재 글자가 다른 경우 append
            print(temp)
    if not temp: # temp에 글자가 남아있지 않다는 것은 글자들이 문제의 조건을 맞게 쌍을 이룬다
        return True
    else:
        return False

def test_check():
    ls = ['ABAB','AABB','ABBA']
    result = 0

    for st in ls:
        data = st
        if check(data):
            result += 1

    assert result == 2