# -*- coding: utf-8 -*-
"""test_baekjoon_11656.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/143bYtoVuTEMSTV09KlGZEuqDqLtemPAX
"""

def suffix(word):
    ls = []
    for i in range(len(word)):
        ls.append(word[i:])
    ls.sort(key = lambda x: x)
    result = ''
    for i in range(len(ls)):
        if i == (len(ls)-1):
            result += ls[i]
        else:
            result += ls[i] + ' '
    return result

def test_suffix():
    assert suffix('baekjoon') == 'aekjoon baekjoon ekjoon joon kjoon n on oon'