# -*- coding: utf-8 -*-
"""test_baekjoon_1920.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fyVZ85QFP39OnIpbB0cAROwqr70QeOSt
"""

def binar(num1,exp,num2,tar):
    exp = list(map(int,exp().split()))
    tar = list(map(int,tar.split()))
    exp.sort()
    for k in tar:
        left, right = 0, len(exp) - 1
        is_find = False
    result = ''
        while True:
            median = (left + right) // 2
            if k == exp[median]:
                result += '1 '
                is_find = True
                break
            elif k > exp[median]:
                left = median + 1
            elif k < exp[median]:
                right = median - 1
            
            if left > right:
                break
        if not is_find:
            result += '0 '

def test_binar():
    assert binar(5,'4 1 5 2 3',5,'1 3 7 9 5') == '1 1 0 0 1 '