# -*- coding: utf-8 -*-
"""test_baekjoon_10815.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ck2E1TjiRyH9C4K5-xxo9sds6Qe1S99Z
"""

def binar(inp, tar)
    result = ''
    inp = list(map(int,inp.split()))
    tar = list(map(int,tar.split()))
    dic = {}
    for i in inp:
        dic[i] = True
    for i in tar:
        if i in dic:
            if i == tar[-1]:
                result += '1'
            else:
                result += '1 '    
        else:
                result += '0'
            else:
                result += '0 '
    return result
def test_binar():
    binar('6 3 2 10 -10','10 9 -5 2 3 4 5 -10') == '1 0 0 1 1 0 0 1'